apiVersion: v1
kind: Service
metadata:
  name: stylish-service
  namespace: stylish-namespace
spec:
  type: NodePort
  selector:
    app: stylish
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
